"""add_deleted_to_examtype

Revision ID: e8a2ca38413e
Revises: 34df859d1d05
Create Date: 2021-01-05 11:01:09.421000

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'e8a2ca38413e'
down_revision = '34df859d1d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examtype', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examtype', 'deleted')
    # ### end Alembic commands ###
